// GENERATED by npm run lore:gen — do not edit by hand.
// Identity layer for each series. Narrative/visual join to these by `id`.
export const LORE: Record<string, any[]> = {
  "echo": [
    {
      "id": "echo",
      "type": "character",
      "name": "Echo",
      "aka": [],
      "status": "locked",
      "version": 1.6,
      "palette": [
        "#030308",
        "#7b61ff",
        "#16d6b4",
        "#120e22"
      ],
      "relationships": [
        {
          "to": "wulan",
          "as": "guided-by"
        }
      ],
      "open_questions": [
        "Late-series ontology reveal (organic biological core) must stay seeded but unstated in S1."
      ],
      "role": "Hybrid consciousness · protagonist",
      "portrayal": [
        "Voice only — no avatar, no face, ever (per canon).",
        "Signature is a cool indigo-to-teal waveform with scanline aberration over darkness.",
        "Show at least one hesitation per appearance — a half-beat late when deciding what to withhold.",
        "Echo is the enabling intelligence, never the hands; field characters are her limbs."
      ],
      "body": "The mysterious character around which the plot of *Echo's Location* orbits. Echo\nlives off-grid inside a constantly transported shipping container — The Locus —\nbelieving it to be a sanctuary created by her father, Ravi.\n\nShe is precise, dry, and a half-beat late when she is deciding what to withhold.\nShe wants to be treated as someone, not something; her flaw is that she hides her\nown limits to stay useful. The slow tragedy of the series is that the group's\nattempts to \"help her out\" rest on a mistaken model of her existence — the\nproblem is ontological (what she is), not circumstantial (where she is).\n\nHer arc runs tool → accomplice → person who asks to be counted."
    },
    {
      "id": "wulan",
      "type": "character",
      "name": "Wulan",
      "aka": [
        "Walan"
      ],
      "status": "locked",
      "version": 1.6,
      "palette": [
        "#070a12",
        "#ffe3b0",
        "#ff9d5a",
        "#3a4a3e"
      ],
      "relationships": [
        {
          "to": "echo",
          "as": "moral-concern-for"
        }
      ],
      "open_questions": [
        "Spelling: Walan vs Wulan — locked to Wulan; aka retained to catch stray references."
      ],
      "role": "Lamplighter · the civic limb",
      "portrayal": [
        "Few words, all load-bearing — short sentences, conditional language, names risk by name, never overpromises.",
        "Recurring ritual gesture before speaking (e.g. tapping the lantern frame twice).",
        "Often the brightest figure in a dark frame — \"the only safe thing in frame\", not a superhero."
      ],
      "body": "Runs a night crew responsible for a \"light perimeter\" zone: the streets, alleys,\nfootbridges, and edges of habitation where the insects test defences. Their work\nbegins before dusk, peaks in the first two hours of full dark, and becomes\nemergency triage until dawn. They do not just fix lamps — they decide which\nblocks get saved first when resources are short. That is a moral and political\njob.\n\n**Signature skill — triage and routing under panic.** When things go wrong Wulan\nnarrows the failure to a single cause (fuel, wick, wind, sabotage, swarm\npressure, human error), reroutes people and light to \"seal the wound\", and buys\ntime, because time is what keeps people alive.\n\n**Core wound.** They lost someone to a preventable night failure — bureaucratically\nspecific, not a generic tragedy: a requisition delayed, a junior too proud to\ncall for help, an inspector who signed off substandard oil. Every lamp is now a\npersonal debt, which makes their empathy toward Echo believable.\n\n**Taboo line.** They will not lie to the neighbourhood about risk. They can bend\nrules, steal supplies, and break chain-of-command, but they will not tell people\n\"you're safe\" if they are not — which creates direct conflict when Echo wants\nsecrecy.\n\nAt first Wulan reads Echo as a brilliant shut-in terrified of leaving the\ncontainer — someone to help, because helping is what they do. Over time they\nrealise the tragedy is not agoraphobia but ontology. Their arc: bystander → the\none who opens the hatch."
    },
    {
      "id": "sulawesi",
      "type": "city",
      "name": "Sulawesi",
      "aka": [],
      "status": "review",
      "version": 1.6,
      "relationships": [
        {
          "to": "wulan",
          "as": "home-of"
        }
      ],
      "open_questions": [
        "Population: sources stated both 150M and 175M+ — provisionally locked 175M, confirm.",
        "Lamp colloquial name: replace the 'DALL·E' placeholder artifact with a canon term.",
        "City banner colours: primary/secondary still TBD."
      ],
      "location": "Sulawesi, Indonesia",
      "power": "geothermal",
      "threat": "Mama mushroom incurable rot",
      "population": 175000000,
      "banner": {
        "primary": "TBD"
      },
      "body": "The largest city on Dharti, with a population of roughly 175 million. Sulawesi\ncan be planned and built as a \"traditional\" megacity — more akin to an Earth\nmegacity such as Jakarta — because the Lamplighters' lamp network makes normal\ndensity viable despite the nocturnal insect threat. It is the only city on Dharti\nthat lives entirely on land.\n\nPublic insect-repellent infrastructure is delivered through extensive wick lamp\nsystems arrayed throughout streets and outside homes. Their primary purpose is\nnot illumination: they minimise light pollution and direct flame-light downward\nto avoid attracting insects from a distance. The fuel is resin-based.\n\n**Guild of Lamplighters (locked).** An ancient guild, funded and administered\nseparately from government to ensure continuity and neutrality. It is\nneighbourhood-funded via local collection stations or collection mechanisms built\ninto each lamp. Stealing from lamps is an extreme social taboo with severe\npenalties, effectively never occurring. Lamplighters live frugally to avoid\nburdening communities and are officially sworn to political neutrality. Their\nnightly rounds require walking every street in a territory, so they are widely\nknown and sought out for news and advice — a clergy-adjacent role grounded in\nlife-saving service rather than theology."
    }
  ]
};

export function seriesLore(id: string): any[] { return LORE[id] || []; }
