// ui.jsx — shared primitives used across stages.

function cx(...a) { return a.filter(Boolean).join(' '); }

// effect color helper
function fxColor(type, l = 0.7, c = 0.16) {
  const hue = (window.EFFECT_TYPES[type] || {}).hue || 280;
  return `oklch(${l} ${c} ${hue})`;
}

function FxChip({ type, on = true, small, onClick, active }) {
  const meta = window.EFFECT_TYPES[type]; if (!meta) return null;
  return (
    <button className={cx('ww-chip', active && 'is-active', !on && 'is-off')} onClick={onClick}
      style={{ '--fx': fxColor(type), '--fxdim': fxColor(type, 0.5, 0.12) }}>
      <span className="ww-chip-g">{meta.glyph}</span>
      {!small && <span>{meta.label}</span>}
    </button>
  );
}

function StateDot({ state }) {
  const map = { Generated: 150, Linked: 200, Draft: 60, Queued: 285 };
  const hue = map[state] != null ? map[state] : 280;
  return <span className="ww-state"><i style={{ background: `oklch(0.72 0.16 ${hue})` }} />{state}</span>;
}

// Reusable thumbnail of a scene with a label overlay (the "generated art" placeholder card)
function AssetThumb({ scene, label, sub, source, state, onClick, selected, tall }) {
  const Scene = window.Scene;
  return (
    <button className={cx('ww-thumb', selected && 'is-sel', tall && 'is-tall')} onClick={onClick}>
      <div className="ww-thumb-art"><Scene kind={scene} /></div>
      <div className="ww-thumb-meta">
        <div className="ww-thumb-top">
          {source && <span className={cx('ww-src', source === 'AI' && 'is-ai')}>{source === 'AI' ? '✦ AI' : source}</span>}
          {state && <StateDot state={state} />}
        </div>
        <div className="ww-thumb-label">{label}</div>
        {sub && <div className="ww-thumb-sub">{sub}</div>}
      </div>
    </button>
  );
}

// the small "generated by AI" placeholder ribbon used on art frames
function PlaceholderTag({ children }) {
  return <div className="ww-ph">{children}</div>;
}

Object.assign(window, { cx, fxColor, FxChip, StateDot, AssetThumb, PlaceholderTag });
