// Generate a single, beautiful top-to-bottom CONSOLIDATED.md per series from the
// per-entity files — so you keep the one-document read of the original canon doc
// while authoring small, diffable, machine-validated files. Generated, never
// hand-edited; regenerate with `npm run lore:gen`.
import type { SeriesLore, LoreEntity } from './_index';

const TYPE_ORDER = ['city', 'character'] as const;
const TYPE_HEADING: Record<string, string> = { city: 'Cities', character: 'Cast' };

function entitySection(e: LoreEntity): string {
  const d = e.data as any;
  const lines: string[] = [];
  lines.push(`### ${d.name}`);
  const meta: string[] = [];
  if (d.role) meta.push(`*${d.role}*`);
  if (d.aka?.length) meta.push(`also: ${d.aka.join(', ')}`);
  meta.push(`status: ${d.status}`);
  lines.push(`<sub>${meta.join(' · ')}</sub>`, '');
  if (e.body) lines.push(e.body, '');
  if (d.portrayal?.length) {
    lines.push('**Portrayal (canon):**');
    for (const p of d.portrayal) lines.push(`- ${p}`);
    lines.push('');
  }
  if (d.relationships?.length) {
    lines.push('**Relationships:** ' + d.relationships.map((r: any) => `${r.as} → ${r.to}`).join(' · '), '');
  }
  if (d.open_questions?.length) {
    lines.push('> **Open:** ' + d.open_questions.join(' / '), '');
  }
  return lines.join('\n');
}

export function consolidate(lore: SeriesLore): string {
  const out: string[] = [];
  out.push(`# ${lore.series} — Consolidated Canon`, '');
  out.push('<!-- GENERATED by npm run lore:gen — do not edit by hand. -->', '');

  const open = lore.all.flatMap((e) =>
    (e.data.open_questions || []).map((q) => `- **${e.data.name}:** ${q}`),
  );
  if (open.length) {
    out.push('## Open Canon Questions', '', ...open, '');
  }

  const byType = new Map<string, LoreEntity[]>();
  for (const e of lore.all) {
    const arr = byType.get(e.data.type) || [];
    arr.push(e);
    byType.set(e.data.type, arr);
  }
  const types = [...TYPE_ORDER, ...[...byType.keys()].filter((t) => !TYPE_ORDER.includes(t as any))];

  for (const t of types) {
    const arr = byType.get(t);
    if (!arr?.length) continue;
    arr.sort((a, b) => a.data.name.localeCompare(b.data.name));
    out.push(`## ${TYPE_HEADING[t] || t}`, '');
    for (const e of arr) out.push(entitySection(e), '');
  }

  return out.join('\n').replace(/\n{3,}/g, '\n\n').trim() + '\n';
}
