// Shared emit step: load + validate all lore, then (re)write every
// CONSOLIDATED.md and the typed src/lore.generated.ts bundle. Throws (LoreError)
// on any schema / id / link error WITHOUT writing the bundle — so a bad mutation
// can be rolled back by the caller before the app sees an inconsistent file.
//
// Used by both the CLI (`_gen.ts` → npm run lore:gen) and the companion server's
// lore store (`_store.ts`) after each write. Kept separate from _gen.ts so the
// server can import it without triggering the CLI's main().
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadAllLore } from './_index';
import { consolidate } from './_consolidate';

const LORE_ROOT = fileURLToPath(new URL('.', import.meta.url));
const SRC = join(LORE_ROOT, '..', 'src');

export function regenerate(): { series: number; entities: number } {
  const lore = loadAllLore();
  let entityCount = 0;

  // consolidated docs
  for (const [series, sl] of lore) {
    writeFileSync(join(LORE_ROOT, series, 'CONSOLIDATED.md'), consolidate(sl));
    entityCount += sl.all.length;
  }

  // typed bundle for the app. Identity only — narrative/visual stay in
  // world.ts and join by id at use-site.
  const bundle: Record<string, any> = {};
  for (const [series, sl] of lore) {
    bundle[series] = sl.all.map((e) => ({ ...e.data, body: e.body }));
  }
  const generated =
    '// GENERATED by npm run lore:gen — do not edit by hand.\n' +
    '// Identity layer for each series. Narrative/visual join to these by `id`.\n' +
    'export const LORE: Record<string, any[]> = ' +
    JSON.stringify(bundle, null, 2) +
    ';\n\nexport function seriesLore(id: string): any[] { return LORE[id] || []; }\n';
  writeFileSync(join(SRC, 'lore.generated.ts'), generated);

  return { series: lore.size, entities: entityCount };
}
