// Build-time entry point: `npm run lore:gen`.
//   1. load + validate all series lore (throws on any schema / id / link error)
//   2. write each series' CONSOLIDATED.md (the human read)
//   3. emit src/lore.generated.ts (the typed bundle the app imports — zero
//      runtime parsing cost, build-time guarantees)
//   4. print the unified resolve() card for one entity as a proof of the join
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadAllLore } from './_index';
import { consolidate } from './_consolidate';
import { resolveEntity } from './_resolve';

const LORE_ROOT = fileURLToPath(new URL('.', import.meta.url));
const SRC = join(LORE_ROOT, '..', 'src');

function main() {
  const lore = loadAllLore();
  let entityCount = 0;

  // (2) consolidated docs
  for (const [series, sl] of lore) {
    writeFileSync(join(LORE_ROOT, series, 'CONSOLIDATED.md'), consolidate(sl));
    entityCount += sl.all.length;
  }

  // (3) typed bundle for the app. Identity only — narrative/visual stay in
  // world.ts and join by id at use-site.
  const bundle: Record<string, any> = {};
  for (const [series, sl] of lore) {
    bundle[series] = sl.all.map((e) => ({ ...e.data, body: e.body }));
  }
  const generated =
    '// GENERATED by npm run lore:gen — do not edit by hand.\n' +
    '// Identity layer for each series. Narrative/visual join to these by `id`.\n' +
    'export const LORE: Record<string, any[]> = ' +
    JSON.stringify(bundle, null, 2) +
    ';\n\nexport function seriesLore(id: string): any[] { return LORE[id] || []; }\n';
  writeFileSync(join(SRC, 'lore.generated.ts'), generated);

  // (4) proof of the join for the slice: echo across all three planes.
  const echo = lore.get('echo');
  if (echo?.byId.has('echo')) {
    const r = resolveEntity(echo, 'echo');
    console.log('\n— unified entity card (proves lore ↔ narrative ↔ visual join) —');
    console.log(`  id:        ${r.id}  (${r.lore.data.name})`);
    console.log(`  lore:      ${r.lore.file}  [${r.lore.data.status}]`);
    console.log(`  narrative: appears in ${r.narrative.appearances.length} ep(s): ` +
      r.narrative.appearances.map((a) => a.episode).join(', '));
    console.log(`             arcs: ${r.narrative.arcs.join(' | ')}`);
    console.log(`  visual:    visdev=${r.visual.visdevId} locked=${r.visual.lockedVariant} ` +
      `variants=${r.visual.variantCount}`);
    console.log(`  portrayal: ${r.portrayal.length} canon rule(s)`);
    if (r.warnings.length) console.log(`  warnings:  ${r.warnings.join('; ')}`);
  }

  console.log(`\n✓ lore: ${lore.size} series, ${entityCount} entities validated → ` +
    `CONSOLIDATED.md + src/lore.generated.ts`);
}

main();
